version: "3.9"
services:
    backend:
        image: overmind-api
        container_name: overmind-api
        build:
            context: ./overmind-api
        ports:
            - "8080:8080"
    frontend:
        image: overmind-ui
        container_name: overmind-ui
        build:
            context: ./overmind-ui
        ports:
            - "4200:80"
        depends_on:
            - backend
    